version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
  ab:
    image: jordi/ab
    command: -c 10 -n 10000 http://nginx:80/
    depends_on: 
        - nginx
  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    environment: 
      - DOCKER_INFLUXDB_INIT_MODE=setup  
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf-metrics
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
    - /://hosfs:ro
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - HOST_ETC=/hostfs/etc
    - HOST_PROC=/hostfs/proc
    - HOST_SYS=/hostfs/sys
    - HOST_VAR=/hostfs/var
    - HOST_RUN=/hostfs/run
    - HOST_MOUNT_PREFIX=/hostfs
volumes:
  influxdbv2: